version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: deployments/test.Dockerfile
    depends_on:
      - db
    environment:
      - TEST_DB_HOST=db
      - TEST_DB_PORT=5432
      - TEST_DB_USER=postgres
      - TEST_DB_PW=mysecretpassword
      - TEST_DB_NAME=tamra-postgis-test
      - TEST_DB_CONNECTION_STRING=postgres://postgres:mysecretpassword@db:5432/tamra-postgis-test?sslmode=disable
    networks:
      - tamra-test-network
  
  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tamra-postgis-test
    networks:
      - tamra-test-network

# Define the network. The reason it is empty is because we want to use the default network driver.
networks:
  tamra-test-network:
