version: 0.2
run-as: root

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip -y
      - apt install upx -y
  pre_build:
    commands:
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -tags lambda.norpc -o bin/bootstrap cmd/tamra/main.go
      - upx --best --lzma bin/bootstrap
      - zip -j bin/tamra.zip bin/bootstrap
  build:
    commands:
      - serverless deploy --stage ${PIPELINE_BRANCH} --region ${PIPELINE_REGION}
      
artifacts:
  files:
    - "**/*"
