version: 0.2
run-as: root

phases:
  install:
    commands:
      - yum install -y zip
      - curl -sL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
      - npm install -g serverless
      - go install github.com/swaggo/swag/cmd/swag@latest
  pre_build:
    commands:
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -tags lambda.norpc -o bin/bootstrap cmd/tamra/main.go
      # TODO: run swagger to generate the docs
      - echo "Zipping the binary file into the root directory of the zip" 
      # The -j flag will store just the file, not the full path. The bootstrap file must be in the root directory of the zip.
      - zip -j bin/bootstrap.zip bin/bootstrap
      - echo "Generating swagger docs"
      - swag init -d ./cmd/tamra,./internal/app/tamra/handlers -g main.go --parseInternal --parseDependency -o docs
      - echo "Zipping the docs directory into the docs directory of the zip"
      - zip -ur bin/bootstrap.zip docs/
      - ls -al bin
  build:
    commands:
      - serverless deploy --stage ${PIPELINE_BRANCH} --region ${PIPELINE_REGION} --verbose
      
artifacts:
  files:
    - "**/*"
