CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    code VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    state VARCHAR(100) NOT NULL DEFAULT 'PENDING',
    restaurant_id VARCHAR(255) REFERENCES restaurants(id) NOT NULL,
    user_id VARCHAR(255) REFERENCES users(id) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE orders 
ADD CONSTRAINT state_check CHECK (state IN ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'FULFILLED', 'CANCELLED'));