CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT,
    state TEXT NOT NULL DEFAULT 'PENDING',
    restaurant_id TEXT REFERENCES restaurants(id) ON DELETE SET NULL,
    user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE orders 
ADD CONSTRAINT state_check CHECK (state IN ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'FULFILLED', 'CANCELLED'));