basePath: /api/v1
definitions:
  models.CreateOrderRequest:
    properties:
      description:
        type: string
    type: object
  models.CreateRestaurantRequest:
    properties:
      latitude:
        type: number
      location_description:
        type: string
      logo_url:
        type: string
      longitude:
        type: number
      name:
        type: string
      phone_number:
        type: string
    required:
    - latitude
    - location_description
    - logo_url
    - longitude
    - name
    type: object
  models.CreateUserRequest:
    properties:
      fcm_token:
        type: string
      is_active:
        description: Pointer to a bool so the validation library doesn't complain
          if the value is false
        type: boolean
      latitude:
        type: number
      longitude:
        type: number
      phone:
        type: string
      radius:
        type: integer
    required:
    - fcm_token
    - is_active
    - latitude
    - longitude
    - phone
    - radius
    type: object
  models.Order:
    properties:
      code:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      restaurant_id:
        type: string
      state:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    required:
    - code
    - restaurant_id
    - state
    - user_id
    type: object
  models.Restaurant:
    properties:
      created_at:
        type: string
      id:
        type: string
      latitude:
        type: number
      location_description:
        type: string
      logo_url:
        type: string
      longitude:
        type: number
      name:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
    required:
    - latitude
    - location_description
    - logo_url
    - longitude
    - name
    type: object
  models.RestaurantLogoUploadResponse:
    properties:
      description:
        type: string
      presigned_url:
        type: string
      stored_file_url:
        type: string
    type: object
  models.UpdateRestaurantRequest:
    properties:
      latitude:
        type: number
      location_description:
        type: string
      logo_url:
        type: string
      longitude:
        type: number
      name:
        type: string
      phone_number:
        type: string
    required:
    - latitude
    - location_description
    - logo_url
    - longitude
    - name
    type: object
  models.UpdateUserRequest:
    properties:
      fcm_token:
        type: string
      is_active:
        type: boolean
      latitude:
        type: number
      longitude:
        type: number
      phone:
        type: string
      radius:
        type: integer
    required:
    - fcm_token
    - is_active
    - latitude
    - longitude
    - phone
    - radius
    type: object
  models.UserResponse:
    properties:
      id:
        type: string
      is_active:
        type: boolean
      last_order_received:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      phone:
        type: string
      radius:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API for the Tamra application
  title: Tamra API
  version: "1"
paths:
  /orders:
    post:
      consumes:
      - application/json
      description: Create a new order with the given request body
      parameters:
      - description: Create Order Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created Order
          schema:
            $ref: '#/definitions/models.Order'
        "400":
          description: Invalid request body
          schema:
            type: string
        "404":
          description: no user to receive order
          schema:
            type: string
        "500":
          description: Failed to create order
          schema:
            type: string
      security:
      - jwt: []
      summary: Create a new order
      tags:
      - orders
  /orders/{id}/accept:
    patch:
      consumes:
      - application/json
      description: Accept a order
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: invalid order ID
          schema:
            type: string
        "500":
          description: failed to accept order
          schema:
            type: string
      security:
      - jwt: []
      summary: Accept a order
      tags:
      - orders
  /orders/{id}/fulfill:
    post:
      consumes:
      - application/json
      description: Fulfill a order
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: invalid order ID
          schema:
            type: string
        "500":
          description: failed to fulfill order
          schema:
            type: string
      security:
      - jwt: []
      summary: Fulfill a order
      tags:
      - orders
  /orders/{id}/reject:
    patch:
      consumes:
      - application/json
      description: Reject a order
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: invalid order ID
          schema:
            type: string
        "500":
          description: failed to reject order
          schema:
            type: string
      security:
      - jwt: []
      summary: Reject a order
      tags:
      - orders
  /orders/{order_id}/cancel:
    patch:
      consumes:
      - application/json
      description: Cancel a order
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: invalid order ID
          schema:
            type: string
        "500":
          description: failed to cancel order
          schema:
            type: string
      security:
      - jwt: []
      summary: Cancel a order
      tags:
      - orders
  /orders/{order_id}/reassign:
    post:
      consumes:
      - application/json
      description: Reassign a order
      parameters:
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: invalid order ID
          schema:
            type: string
        "500":
          description: failed to reassign order
          schema:
            type: string
      security:
      - jwt: []
      summary: Reassign a order
      tags:
      - orders
  /orders/restaurant:
    get:
      consumes:
      - application/json
      description: Get all orders for a restaurant
      produces:
      - application/json
      responses:
        "200":
          description: Restaurant Orders
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "404":
          description: order not found
          schema:
            type: string
        "500":
          description: failed to get orders
          schema:
            type: string
      security:
      - jwt: []
      summary: Get all orders for a restaurant
      tags:
      - orders
  /orders/user:
    get:
      consumes:
      - application/json
      description: Get all orders for a user
      produces:
      - application/json
      responses:
        "200":
          description: User Orders
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
        "404":
          description: order not found
          schema:
            type: string
        "500":
          description: failed to get orders
          schema:
            type: string
      security:
      - jwt: []
      summary: Get all orders for a user
      tags:
      - orders
  /restaurants:
    post:
      consumes:
      - application/json
      description: Create a new restaurant with the given request body
      parameters:
      - description: Create Restaurant Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateRestaurantRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created Restaurant
          schema:
            $ref: '#/definitions/models.Restaurant'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create restaurant
          schema:
            type: string
      security:
      - jwt: []
      summary: Create a new restaurant
      tags:
      - restaurants
  /restaurants/{restaurantID}:
    get:
      description: Get a restaurant by the restaurant ID
      parameters:
      - description: Restaurant ID
        in: path
        name: restaurantID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Restaurant
          schema:
            $ref: '#/definitions/models.Restaurant'
        "404":
          description: Restaurant not found
          schema:
            type: string
        "500":
          description: Failed to get restaurant
          schema:
            type: string
      security:
      - jwt: []
      summary: Get a restaurant by ID
      tags:
      - restaurants
  /restaurants/logo/uploadurl:
    get:
      description: Get a signed URL to upload a restaurant logo to the S3 bucket
      produces:
      - application/json
      responses:
        "200":
          description: Presigned URL
          schema:
            $ref: '#/definitions/models.RestaurantLogoUploadResponse'
        "500":
          description: Failed to get upload URL
          schema:
            type: string
      security:
      - jwt: []
      summary: Get a signed URL to upload a restaurant logo
      tags:
      - restaurants
  /restaurants/me:
    delete:
      description: Delete a restaurant
      responses:
        "204":
          description: Restaurant deleted
          schema:
            type: string
        "500":
          description: Failed to delete restaurant
          schema:
            type: string
      security:
      - jwt: []
      summary: Delete a restaurant
      tags:
      - restaurants
    get:
      description: Get a restaurant by the user ID
      produces:
      - application/json
      responses:
        "200":
          description: Restaurant
          schema:
            $ref: '#/definitions/models.Restaurant'
        "404":
          description: Restaurant not found
          schema:
            type: string
        "500":
          description: Failed to get restaurant
          schema:
            type: string
      security:
      - jwt: []
      summary: Get a restaurant
      tags:
      - restaurants
    patch:
      consumes:
      - application/json
      description: Update a restaurant with the given request body
      parameters:
      - description: Update Restaurant Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateRestaurantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated Restaurant
          schema:
            $ref: '#/definitions/models.Restaurant'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to update restaurant
          schema:
            type: string
      security:
      - jwt: []
      summary: Update a restaurant
      tags:
      - restaurants
  /users:
    post:
      consumes:
      - application/json
      description: Create a user
      parameters:
      - description: Create User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created User
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create user
          schema:
            type: string
      security:
      - jwt: []
      summary: Create a user
      tags:
      - users
  /users/me:
    delete:
      description: Delete a user
      responses:
        "200":
          description: User deleted
          schema:
            type: string
        "500":
          description: Failed to delete user
          schema:
            type: string
      security:
      - jwt: []
      summary: Delete a user
      tags:
      - users
    get:
      description: Get a user by the user ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "404":
          description: user not found
          schema:
            type: string
        "500":
          description: failed to get user
          schema:
            type: string
      security:
      - jwt: []
      summary: Get a user
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update a user
      parameters:
      - description: Update User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated User
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to update user
          schema:
            type: string
      security:
      - jwt: []
      summary: Update a user
      tags:
      - users
schemes:
- http
- https
securityDefinitions:
  jwt:
    description: Bearer token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
